### PR TITLE
Upgrade Clerk

### LINKED ISSUE #15: Clay & clerk is broken on clerk upgrade: No such var: view/->result
```
2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling scicloj/clay/v1/tool/clerk.clj at (38:20)
   #:clojure.error{:phase :compile-syntax-check,
                   :line 38,
                   :column 20,
                   :source "scicloj/clay/v1/tool/clerk.clj"}
             Compiler.java: 6825  clojure.lang.Compiler/analyze
             ...
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  202  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  201  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  833  java.lang.Thread/run

1. Caused by java.lang.RuntimeException
   No such var: view/->result

                 Util.java:  221  clojure.lang.Util/runtimeException
             Compiler.java: 7405  clojure.lang.Compiler/resolveIn
             Compiler.java: 7375  clojure.lang.Compiler/resolve
             ...
             Compiler.java: 7653  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load
                   RT.java:  424  clojure.lang.RT/load
                  core.clj: 6161  clojure.core/load/fn
                  core.clj: 6160  clojure.core/load
                  core.clj: 6144  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5933  clojure.core/load-one
                  core.clj: 5928  clojure.core/load-one
```
I believe the following commit broke it 🔥  :
https://github.com/nextjournal/clerk/commit/133c32c608078ab8cc5d90b3eb762be2b8556791#diff-8950130d83008fae9fd570854a759d6542375816ee6c4b647cae8f1cecdd276dL84

as it is using the following: 
https://github.com/scicloj/clay/blob/main/src/scicloj/clay/v1/tool/clerk.clj#L38

### PR DESCRIPTION
**Pull request by mk**
This upgrades Clerk to the latest version and should hopefully fix #15.

I haven't been able to test it though as I ran into other seemingly unrelated problems regarding scittle.

@daslu or @dmg46664 can you maybe take this for a spin?

### CODE REVIEW

**Comment by dmg46664** [comment]
@mk  Thanks!
Those scittle changes scampered me too! I needed to make a few changes include clerk references to get it to run which you can see here: https://github.com/dmg46664/clay/commit/f6a4d45b89766e50ec4d93f28d8f4b8a0f94f118

Echarts works great now ✅ 
However, it doesn't look like clay itself is working in terms of bypassing clerk to immediately update the eval'd sexp.
I haven't changed my emacs clay config, so assumed it would have just worked 🤷

**Comment by daslu** [comment]
@mk @dmg46664 thanks for this great help. 

I'll look today more closely. :pray:

**Comment by daslu** [comment]
@dmg46664 @mk thanks again for the kind help!

To clarify the current situation, currently the older version of Clerk can be used with Clay in three different ways.
1. as the Clerk notebook tool with Clay's viewer adaptations (providing, e.g., a default way of rendering tech.ml.dataset datasets and Viz.clj plots)
2. as a data visualization tool for viewing one value in a page (following the same adapted viewer semantics)
3. as a computation engine, passing a namespace's evaluated forms (and its comments rendered as hiccup) to a page rendered by the Scittle tool (used to render pages like the [Clay Intro](https://scicloj.github.io/clay/) and [Viz.clj Intro](https://scicloj.github.io/viz.clj))

My current way of testing all of these is making sure the [intro](https://github.com/scicloj/clay/blob/main/notebooks/intro.clj) works.
All three uses seem to need more care to work with the current Clerk. I will give it a try.

Of course, this project has been knowingly uncareful, relying on Clerk internals. This was an important choice on our path to demonstrating the desired behavior. Of course, it was a problematic choice.

The current plans are briefly as follows:
1. In the coming few weeks, figure out a working version of Clay. Possibly, we'll have to compromise and only have some of the relevant tools working -- some subset of #{portal, clerk, oz, scittle}.
2. In the months following that, mostly work on creating & teaching content, such as the [ds4clj](https://scicloj.github.io/docs/community/groups/ds4clj/) course.
3. If and when time allows, work on adapters to relevant tools, to make them usable with that content.

**Comment by dmg46664** [comment]
@daslu Thanks. I think a lot of what you've written refers to a larger roadmap.

> My current way of testing all of these is making sure the [intro](https://github.com/scicloj/clay/blob/main/notebooks/intro.clj) works.
All three uses seem to need more care to work with the current Clerk. I will give it a try.

The above appears to be the relevant bit to this Clerk issue. I'd just add that I'd prefer to have a regression of Clay<->Clerk features merged in order to stabilise working with a later version of Clerk, than keep it locked to a previous stable version. The latter increases the pain of attempting to integrate with a later version by kicking the can further and further down the road.

**Comment by daslu** [comment]
Thanks, @dmg46664.

I shared this broader picture to clarify the current priorities and reflect the fact that some compromises will be needed in the short term (e.g., possibly not keeping up with Clerk's fast developments).

> a regression of Clay<->Clerk features 

Could you explain what kind of regression you have in mind?

**Comment by dmg46664** [comment]
@daslu Sure. In my testing, echarts worked on Clay but the nrepl instant update hack didn't.
I'd be good with taking this PR simply for the purpose of upgrading Clay... rather than letting the PR languish until every feature was working. (This is on the assumption that Clerk doesn't make the subset you talk about. I.e. Clerk @75% > 0xClerk. Obviously if you have time to investigate the instant update, then no languishing PR and this conversation is moot 😅  )

**Comment by daslu** [comment]
@dmg46664 thanks. It helps very much to know about your usage priorities.

Of the above 3 uses of Clerk in Clay:

> 1. as the Clerk notebook tool with Clay's viewer adaptations (providing, e.g., a default way of rendering tech.ml.dataset datasets and Viz.clj plots)
> 2. as a data visualization tool for viewing one value in a page (following the same adapted viewer semantics)
> 3. as a computation engine, passing a namespace's evaluated forms (and its comments rendered as hiccup) to a page rendered by the Scittle tool (used to render pages like the [Clay Intro](https://scicloj.github.io/clay/) and [Viz.clj Intro](https://scicloj.github.io/viz.clj))

1 is partially working for me, and 2,3 are not working.

3 is something we cannot drop since it is needed in the Scittle tool.
2 seems important as well.

Therefore, the current PR version is not something we could merge.
I am trying to solve things, but not sure yet if I can make it with the limited time I currently have.

**Comment by dmg46664** [comment]
@daslu  Thanks for the explanation of the product requirements.

Food for thought: I recommend a handful of integration tests in order to protect only the most necessary features in the future, and know immediately breaking changes in dependencies. (Funnily the smaller the available dev resource, the more important 1 or 2 tests are).

**Comment by daslu** [comment]
Thanks, @dmg46664, you are so right about that.

**Comment by mk** [comment]
It looks like Clerk is no longer being used as of #19 so I believe this PR is no longer relevant and I'm closing it. @daslu if that's not the case let me know and we can revisit it.

**Pull request closed without merging**
