### PR TITLE
eval code before form, forms may have expanded `

### PR DESCRIPTION
**Pull request by timothypratley**
See discussion here:

https://clojurians.zulipchat.com/#narrow/stream/422115-clay-dev/topic/macro.20expansion.20takes.20place.20in.20the.20ns.20calling.20make!

### CODE REVIEW

**Comment by timothypratley** [comment]
https://github.com/scicloj/clay/issues/132

**Comment by timothypratley** [comment]
https://github.com/scicloj/clay/issues/92

**Comment by holyjak** [comment]
I've verified that this fixes my problem.

**Comment by daslu** [comment]
Also tested it in various cases.

Looks great.

**Pull request merged**
