### PR TITLE
Watch notebook files and live reload pages if changed.

### LINKED ISSUE #160: [Feature Request]Live update and reload while editing the notebooks
It seems clay can't update the html page and reload it automatically when the notebook file is updated, though it has a websocket connection connected.

It would be much better to have this feature so that folks can focus on creating the content.

### PR DESCRIPTION
**Pull request by whatacold**
This is trying to fix #160.

### CODE REVIEW

**Comment by daslu** [comment]
Thanks for these additions, @whatacold!

I hope to merge this before the next release during the weekend.

**Comment by whatacold** [comment]
No rush, just take your time.

Since `source-path` could be a vector, I'm still trying to think of a proper way to handle this case.

**Comment by whatacold** [comment]
> Since `source-path` could be a vector, I'm still trying to think of a proper way to handle this case.

This has been added, I would love to hear what you think, thanks.

**Comment by daslu** [comment]
Thanks, @whatacold!

Mergingb

**Pull request merged**
